Changes for test

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -27,7 +27,7 @@ jobs:
         run: |
           aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
 
-      - name: Build Docker image
+      - name: Build Docker image for testing
         env:
           ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
           ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
@@ -37,14 +37,15 @@ jobs:
           IMAGE_TAG=develop
           docker build --file $FILE -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
 
-      - name: Run Docker container
+      - name: Run Docker container for testing
         run: |
           docker run -d -p 5000:5000 ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:develop
-
-      - name: Test Docker container
-        run: |
-          sleep 10
+          sleep 5
           curl --fail http://localhost:5000 || exit 1
+      # - name: Test Docker container
+      #   run: |
+          # sleep 10
+          # curl --fail http://localhost:5000 || exit 1
 
       - name: Push Docker image to ECR
         if: success()
